apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: dns-svc-key
  name: dns-udp-svc
  namespace: kube-system
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.5
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
