repositories:
  # Official "stable" charts
  - name: stable
    url: https://charts.helm.sh/stable
  # Chartmuseum repo
  - name: jetstack
    url: https://charts.jetstack.io
  # Harbor repo
  - name: harbor
    url: https://helm.goharbor.io

releases:
  - name: nginx-ingress
    namespace: nginx-ingress
    createNamespace: true
    chart: stable/nginx-ingress
    version: 1.41.3

  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: 0.16.1
    wait: true
    set:
      - name: installCRDs
        value: true
    hooks:
      - events: ["postsync"]
        command: "kubectl"
        args: ["apply", "-f", "./cluster-issuer.yaml"]
        showlogs: true

  - name: chartmuseum
    namespace: chartmuseum
    createNamespace: true
    chart: stable/chartmuseum
    version: 2.13.2
    values:
      - ./values-chartmuseum.yaml
    wait: true

  - name: harbor
    namespace: harbor
    createNamespace: true
    chart: harbor/harbor 
    values:
      - ./values-harbor.yaml
    wait: true






