apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.containerPort }}
  selector:
    name: front-end