apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shop
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
  labels:
    app: frontend
spec:
  defaultBackend:
    service:
      name: frontend
      port:
        number: {{ .Values.service.port }}
  rules:
  - host: {{ .Values.ingress.host }} 
    http: 
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend
            port:
              number: {{ .Values.ingress.port }}
